// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlhsbeokhxleffybkkzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1saHNiZW9raHhsZWZmeWJra3p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMTMzODIsImV4cCI6MjA2Njc4OTM4Mn0.Kl9hlSEJsVYlZm6ytvoTRvH5qQB0InCkBeC3lMCYDNg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);